### ISSUE TITLE
Error when call nodes in maven

### ISSUE THREAD

**Issue by YasCoMa** [Data2Semantics/nodes#1]
Other repositories that depend on nodes do not work because the nodes-SNAPSHO.jar is missing. And the direct reference to the last code version of nodes algo generates errors in the files.

**Comment by pbloem** [comment]
Hi Yassmin,

Thanks for the pointer. I think the problem is that some repositories point our old build server (which never really worked). Can you check that the repository you're trying to compile uses jitpack to point to nodes, as shown in the README?

If it does can you give me a pointer to the pom file of the repository? 

cheers,
  Peter

**Comment by YasCoMa** [comment]
Yes. It uses jitpack.
The pointer to the nodes pom file is: https://github.com/Data2Semantics/nodes/blob/master/nodes/pom.xml
And the address for the pom file of the repository that uses nodes is: https://github.com/Data2Semantics/mustard/blob/master/mustard-kernels/pom.xml

**Comment by pbloem** [comment]
It looks like reference to a local version of pbloem/kit had snuck into the POM.  -SNAPSHOT should now work again.

Alternatively, you could also change the pom in mustard-kernel from -SNAPSHOT to v0.1.20.

**Comment by YasCoMa** [comment]
Problem solved.
